const FETCH_ATTENDEES = "FETCH_ATTENDEES";
const FETCH_ATTENDEES_SUCCEEDED = "FETCH_ATTENDEES_SUCCEEDED";
const FETCH_ATTENDEES_FAILED = "FETCH_ATTENDEES_FAILED";

export {
  FETCH_ATTENDEES,
  FETCH_ATTENDEES_SUCCEEDED,
  FETCH_ATTENDEES_FAILED,
};
