const FETCH_WAITLIST = "FETCH_WAITLIST";
const FETCH_WAITLIST_SUCCEEDED = "FETCH_WAITLIST_SUCCEEDED";
const FETCH_WAITLIST_FAILED = "FETCH_WAITLIST_FAILED";

export {
  FETCH_WAITLIST,
  FETCH_WAITLIST_SUCCEEDED,
  FETCH_WAITLIST_FAILED,
};
